version: "3.7"

services:
    sq:
        image: mcr.microsoft.com/mssql/server:2017-latest
        container_name: sql1
        hostname: sql1
        ports:
            - 1433:1433
        volumes:
            - ../Sql1DockerVolumes/data:/var/opt/mssql/data
            - ../Sql1DockerVolumes/log:/var/opt/mssql/log
            - ../Sql1DockerVolumes/secrets:/var/opt/mssql/secrets 
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=Password1

# start the docker image: 
# me@mymachine:~/EFQ$ cd EFQ.Infrastructure
# me@mymachine:~/EFQ/EFQ.Infrastructure$ docker-compose up -d
#
# Change the SA password:
# me@mymachine:~/EFQ/EFQ.Infrastructure$ docker exec -it sql1 /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P "Password1" -Q 'ALTER LOGIN SA WITH PASSWORD="Password1"'
#
# Open a shell in the docker image:
# me@mymachine:~/EFQ/EFQ.Infrastructure$ docker exec -it sql1 "bash"
#
# Run sqlcmd in the image (sqlcmd is not in $PATH so you need to specify full path):
# root@sql1# /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P "Password1"
